# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 140ff962897bf9e7a208df32666e7d094935def363ee4fb6b8fb0ec567a3a0a04ff305df6519520df2abfef6e4ff1ed97f6a59da45927b4d81f17e4a96e93a19

test:
  secret_key_base: daf0065654fa062a2de3b685f005b51ca53a59bb82bfae9a6cb9098e7fb1567f7a9269a133c4187f4784ade6f2b1494c8e3d7f9ebc3d3a1d7995fe1ddfc8e8ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
